var config = {
    texts: [
        "Today is...",      
        "as beautiful as other days",  
        "but you realize",
        "another year has gone",
        "in a blink of the eyes",
        "This I actually made",
        "as a birthday gift to you 😆",
        "I just want to say",
        "thanks for the friendship we made",
        "thanks for clearing all the useless doubts, I used to ask 😆",
        "I wish you all the best ✨",
        "May your life be at ease",
        "May all your wishes come true",
        "Remember",
        "your ambitions",
        "you live as a free bird...",
        "flying in the blue sky",
        "Now things are different...",
        "real story of your life",
        "is just about to begin",
        "indeed..",
        "but...",
        "don't worry",
        "because...",
        "God has your back",
        "and I hope",
        "you'll find...",
        "happiness along the way",
        "keep your spirit up",
        "enjoy every single moment...",
        "and fill it with your most beautiful smile",
        "lastly...",
        "I'd like to wish you one more time",
        "a very happy birthday Keeerr JI 🥳",
        "There's also a Keer ChatBOT at the bottom, do check 🙈"

    ],

    imgs: {
        "心爱的小可爱": "./imgs/keer.png",
    },
    desc: {
        turn_on: "🏮 TURN ON LIGHTS 🏮",
        play: "🎻 PLAY MUSIC 🎻",
        bannar_coming: "🎊 LET'S DECORATE 🎊",
        balloons_flying: "🎈 FLY WITH BALLOONS 🎈",
        cake_fadein: "🎂 MOST DELICIOUS CAKE EVER 🎂",
        light_candle: "🕯 LIGHT CANDLE 🕯",
        wish_message: "🎉 HAPPY BIRTHDAY 🎉",
        story: "✨ MESSAGE FOR YOU ✨",
    }
};
