var config = {
    texts: [
        "Today is...",      
        "as beautiful as other days",  
        "but you realize",
        "another year has gone",
        "in a blink of the eyes",
        "however",
        "Do you know..?",
        "today is just special",
        "so special to you",
        "that's why",
        "Let's make it...",
        "the best celebration ever",
        "and let me share...",
        "a piece of happiness to you",
        "I made all this...",
        "as a birthday present to you",
        "thanks for being there",
        "thanks for the friendship we made",
        "thanks for everything",
        "I wish you all the best",
        "May your life be at ease",
        "May all your wishes come true",
        "Remember",
        "your ambitions",
        "you live as a free bird...",
        "flying in the blue sky",
        "Now things are different...",
        "real story of your life",
        "is just about to begin",
        "indeed..",
        "lastly...",
        "I'd like to wish you one more time",
        "a very happy birthday Keeerr JI"
    ],

    imgs: {
        "心爱的小可爱": "./imgs/xiaokeai.png",
    },
    desc: {
        turn_on: "🏮 TURN ON LIGHTS 🏮",
        play: "🎻 PLAY MUSIC 🎻",
        bannar_coming: "🎊 LET'S DECORATE 🎊",
        balloons_flying: "🎈 FLY WITH BALLOONS 🎈",
        cake_fadein: "🎂 MOST DELICIOUS CAKE EVER 🎂",
        light_candle: "🕯 LIGHT CANDLE 🕯",
        wish_message: "🎉 HAPPY BIRTHDAY 🎉",
        story: "✨ MESSAGE FOR YOU ✨",
    }
};
